// flaglib.js - turns a correct result into a flag. You do NOT edit this file.
//
// A flag is HAU{...}. It is computed from the VALUE your code produces at run
// time (never stored here), so the only way to get the right flag is to make
// your code produce the right result. Paste each flag into the Canvas exam.
import { createHash } from 'node:crypto'

const SALT = 'HAUNTED-2026-MIDTERM'

// Stable string form of a value: object keys are sorted and Dates become their
// ISO string, so the same data always hashes to the same flag.
function stable(v) {
  if (v instanceof Date) return JSON.stringify(v.toISOString())
  if (Array.isArray(v)) return '[' + v.map(stable).join(',') + ']'
  if (v && typeof v === 'object') {
    return '{' + Object.keys(v).sort().map(k => JSON.stringify(k) + ':' + stable(v[k])).join(',') + '}'
  }
  return JSON.stringify(v)
}

export function makeFlag(name, value) {
  const h = createHash('sha256').update(`${SALT}:${name}:${stable(value)}`).digest('hex').slice(0, 10)
  return `HAU{${h}}`
}
